// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"EventCommandByCode","status":true,"description":"Plugin for Event Command Execution via Code Specification","parameters":{}},
{"name":"QuanPing","status":true,"description":"游戏根据屏幕分辨率自动扩充全屏","parameters":{"分辨率高度":"624"}},
{"name":"MVJoint","status":true,"description":"ツクールMZ上でMVのプラグインを無理やり動かします。","parameters":{}},
{"name":"ALOE_VirtualButtons","status":true,"description":"v2.0.1 Creates buttons on the screen for touch input","parameters":{"dPadSettings":"{\"image\":\"D-Pad\",\"hotImage\":\"Hot-D-Pad\",\"activeScenes\":\"[\\\"Scene_Title\\\",\\\"Scene_Map\\\"]\",\"x\":\"25\",\"y\":\"340\",\"soundEffect\":\"\"}","keyButtonSettings":"[\"{\\\"name\\\":\\\"Z\\\",\\\"inputMethod\\\":\\\"0\\\",\\\"inputTrigger\\\":\\\"ok\\\",\\\"image\\\":\\\"Z\\\",\\\"hotImage\\\":\\\"Hot-Z\\\",\\\"activeScenes\\\":\\\"[\\\\\\\"Scene_Title\\\\\\\",\\\\\\\"Scene_Map\\\\\\\"]\\\",\\\"x\\\":\\\"500\\\",\\\"y\\\":\\\"450\\\",\\\"soundEffect\\\":\\\"\\\",\\\"commonEvent\\\":\\\"0\\\",\\\"customCode\\\":\\\"\\\",\\\"vibratePattern\\\":\\\"0\\\"}\",\"{\\\"name\\\":\\\"X\\\",\\\"inputMethod\\\":\\\"0\\\",\\\"inputTrigger\\\":\\\"escape\\\",\\\"image\\\":\\\"X\\\",\\\"hotImage\\\":\\\"Hot-X\\\",\\\"activeScenes\\\":\\\"[\\\\\\\"Scene_Title\\\\\\\",\\\\\\\"Scene_Map\\\\\\\"]\\\",\\\"x\\\":\\\"650\\\",\\\"y\\\":\\\"450\\\",\\\"soundEffect\\\":\\\"\\\",\\\"commonEvent\\\":\\\"0\\\",\\\"customCode\\\":\\\"\\\",\\\"vibratePattern\\\":\\\"0\\\"}\"]","controlButtonSettings":"{\"image\":\"Menu\",\"activeScenes\":\"[\\\"Scene_Title\\\",\\\"Scene_Map\\\"]\",\"x\":\"0\",\"y\":\"0\",\"soundEffect\":\"\",\"buttonsToHide\":\"[]\",\"hideDPad\":\"true\"}","fadeDuration":"20","fadeDelay":"1","disableTouchWindows":"[\"\"]","disableTouchMovement":"true","enableDiagonalInput":"true","hideButtonsDuringDialogue":"true","enableDPadDebugWindow":"false"}}
];
